name: post_app
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=2.19.1 <3.0.0'
dependencies:
  
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  
  # Http Client
  dio: ^5.0.1
  # Value equality
  equatable: ^2.0.5
  # Adaptive screen
  flutter_screenutil: ^5.6.1
  # Navigation manager
  go_router: ^6.2.0
  # Checking network connectivity
  internet_connection_checker: ^1.0.0+1
  # Logging data in debug mode
  logger: ^1.2.2
  # Showing Toast message
  oktoast: ^3.3.1
  # Functional programming
  dartz: ^0.10.1
  # Local database
  shared_preferences: ^2.0.18
  # Dependency Injection
  get_it: ^7.2.0
  # State management
  flutter_bloc: ^8.1.2
  # Caching images from network
  cached_network_image: ^3.2.3
  # Date formatting
  intl: ^0.18.0
  # Webview
  webview_flutter: ^4.0.5

  
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
